name: main

on: [push, pull_request] # Trigger when someone pushs or dens PR

# 3 Jobs, packages, deploy, notify
jobs:
  package:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Publish (Release Mode)
        run: dotnet publish GhisTrader/src/GhisTrader  -o ${{ github.workspace }}/bin/Publish --configuration Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true

      - name: Generate changelog
        run: echo "#Good things are comming" > ${{github.workspace}}-CHANGELOG.txt

      - name: Dispay some values
        run: |
          echo  "ref_type ====> ${{github.ref_type }}"
          echo  " workspace====> ${{ github.workspace }}"
          echo  "  github.ref ====> ${{  github.ref}}"
          echo  " event_name ====> ${{ github.event_name}}"
          more  ${{github.workspace}}-CHANGELOG.txt

      - name: Publish your  package
        uses: actions/upload-artifact@v3
        with:
          name: GhisTrader
          path: ${{ github.workspace }}/bin/Publish
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
  deploy:
    if: ${{ github.event_name == 'push' && github.ref_type == 'branch' }}
    needs: package # Dependent of jobs packages
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: GhisTrader
          path: GhisTrader

      - name: Create package
        run: Compress-Archive -Path GhisTrader/* -DestinationPath GhisTrader.zip -Force
        shell: pwsh

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }} # How to set  tag name?
          release_name: ${{ github.ref }} # How to set  release name?
          body: |
            [Changelog](https://github.com/Ghislain1/GhisTrader/blob/master/CHANGELOG.md)
          draft: true # Later to false
          prerelease: true # Later to false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: GhisTrader.zip
          asset_path: GhisTrader.zip
          asset_content_type: application/zip
